/** FreshMart POS — returns & exchanges extension. */
var RETURNS_VERSION = '1.0.0';
var RETURNS_SCHEMA = {
  Returns: [['id','n'],['returnNo','s'],['createdAt','d'],['invoiceNo','s'],['saleId','n'],['customerName','s'],['type','s'],['settlementMethod','s'],['refundAmount','n'],['difference','n'],['status','s'],['itemCount','n'],['reason','s']],
  ReturnItems: [['id','n'],['returnId','n'],['invoiceNo','s'],['originalSaleItemId','n'],['productId','n'],['sku','s'],['name','s'],['unit','s'],['qty','n'],['unitPrice','n'],['taxRate','n'],['replacementProductId','n'],['replacementSku','s'],['replacementName','s'],['replacementQty','n'],['replacementPrice','n'],['replacementTaxRate','n'],['reason','s']],
  ReturnsSyncLog: [['opId','s'],['appliedAt','d'],['ok','b'],['message','s']]
};
if (typeof ACTIONS !== 'undefined') {
  ACTIONS.returnsBootstrap = returnsBootstrap_;
  ACTIONS.returnsCreate = function (r) { return withLock_(function () { return returnsCreate_(r); }); };
  ACTIONS.returnsSync = function (r) { return withLock_(function () { return returnsSync_(r); }); };
}
function returnsSetupSheet_(name) { var ss=ss_(),sh=ss.getSheetByName(name)||ss.insertSheet(name),cols=RETURNS_SCHEMA[name]; if(sh.getLastRow()===0){sh.getRange(1,1,1,cols.length).setValues([cols.map(function(c){return c[0];})]).setFontWeight('bold').setBackground('#2563eb').setFontColor('#ffffff');sh.setFrozenRows(1);}else{var have=sh.getRange(1,1,1,cols.length).getValues()[0];for(var i=0;i<cols.length;i++)if(!have[i])sh.getRange(1,i+1).setValue(cols[i][0]).setFontWeight('bold').setBackground('#2563eb').setFontColor('#ffffff');}return sh; }
function returnsRead_(name){var sh=returnsSetupSheet_(name),cols=RETURNS_SCHEMA[name],last=sh.getLastRow();if(last<2)return[];var vals=sh.getRange(2,1,last-1,cols.length).getValues(),out=[];vals.forEach(function(row,i){var o={_row:i+2};cols.forEach(function(c,j){var v=row[j];if(c[1]==='n')v=Number(v)||0;else if(c[1]==='b')v=v===true||String(v).toLowerCase()==='true';else if(c[1]==='d')v=v?new Date(v).toISOString():null;else v=v==null?'':String(v);o[c[0]]=v;});if(name==='ReturnsSyncLog'||o.id>0)out.push(o);});return out;}
function returnsAppend_(name,objs){if(!objs.length)return;var sh=returnsSetupSheet_(name),cols=RETURNS_SCHEMA[name];sh.getRange(sh.getLastRow()+1,1,objs.length,cols.length).setValues(objs.map(function(o){return cols.map(function(c){var v=o[c[0]];if(c[1]==='n')return Number(v)||0;if(c[1]==='b')return!!v;if(c[1]==='d')return v?new Date(v):'';return v==null?'':String(v);});}));}
function returnsStr_(v,n){return String(v==null?'':v).trim().slice(0,n||200);}
function returnsNum_(v){var n=Number(v);return isFinite(n)?n:0;}
function returnsR2_(n){return Math.round((Number(n)||0)*100)/100;}
function returnsR3_(n){return Math.round((Number(n)||0)*1000)/1000;}
function returnsBootstrap_(){return{version:RETURNS_VERSION,returns:returnsRead_('Returns'),returnItems:returnsRead_('ReturnItems')};}
function returnsCreate_(req){
  var invoiceNo=returnsStr_(req.invoiceNo,40);if(!invoiceNo)throw new Error('Invoice number is required');
  var salesRows=findRows_('Sales','invoiceNo',invoiceNo);if(!salesRows.length)throw new Error('Invoice '+invoiceNo+' not found');
  var sale=readRow_('Sales',salesRows[0]);if(sale.status==='voided')throw new Error('A voided invoice cannot be returned');
  var input=Array.isArray(req.items)?req.items:[];if(!input.length)throw new Error('Select at least one item');if(input.length>MAX_CART_LINES)throw new Error('Too many return lines');
  var existing=returnsRead_('ReturnItems'),bySaleItem={};existing.forEach(function(x){if(String(x.invoiceNo).toLowerCase()===invoiceNo.toLowerCase())bySaleItem[x.originalSaleItemId]=(bySaleItem[x.originalSaleItemId]||0)+returnsR3_(x.qty);});
  var saleItems=itemsForSale_(sale.id),byId={};saleItems.forEach(function(x){byId[x.id]=x;});
  var iso=new Date().toISOString(),type=req.type==='exchange'?'exchange':'return',returnedValue=0,replacementValue=0,prepared=[];
  input.forEach(function(x){var original=byId[Number(x.originalSaleItemId)];if(!original)throw new Error('Original sale item not found');var qty=returnsR3_(x.qty),remaining=returnsR3_(Number(original.qty)-Number(bySaleItem[original.id]||0));if(!(qty>0)||qty>remaining)throw new Error(original.name+': return quantity exceeds the remaining returnable quantity ('+remaining+')');var tax=returnsNum_(original.taxRate),unitPrice=returnsNum_(original.price);returnedValue+=qty*unitPrice*(1+tax/100);var replacement=null,replacementQty=returnsR3_(x.replacementQty);if(type==='exchange'){replacement=resolveProduct_(readTable_('Products'),x.replacementProductId,x.replacementSku);if(!replacement)throw new Error('Replacement product not found');if(!(replacementQty>0))throw new Error('Enter a replacement quantity for '+replacement.name);if(returnsNum_(replacement.stock)<replacementQty)throw new Error('Not enough stock for '+replacement.name+' (available: '+replacement.stock+' '+replacement.unit+')');replacementValue+=replacementQty*returnsNum_(replacement.price)*(1+returnsNum_(replacement.taxRate)/100);}prepared.push({original:original,qty:qty,replacement:replacement,replacementQty:replacementQty,unitPrice:unitPrice,taxRate:tax});});
  var difference=type==='exchange'?returnsR2_(replacementValue-returnedValue):returnsR2_(-returnedValue),settlement=['cash','card','upi'].indexOf(req.settlementMethod)>=0?req.settlementMethod:'cash';
  var returnId=returnsRead_('Returns').reduce(function(m,r){return Math.max(m,Number(r.id)||0);},0)+1,returnNo='RET-'+Utilities.formatDate(new Date(),tz_(),'yyyyMMdd')+'-'+String(returnId).padStart(5,'0');
  var rec={id:returnId,returnNo:returnNo,createdAt:iso,invoiceNo:invoiceNo,saleId:sale.id,customerName:returnsStr_(sale.customerName,80),type:type,settlementMethod:settlement,refundAmount:difference<0?Math.abs(difference):0,difference:difference,status:'Completed',itemCount:prepared.length,reason:returnsStr_(req.reason,120)};
  var nextItem=returnsRead_('ReturnItems').reduce(function(m,r){return Math.max(m,Number(r.id)||0);},0),rows=[],moves=[],products=readTable_('Products'),nextMove=lastId_('StockMovements');
  prepared.forEach(function(x){var p=resolveProduct_(products,x.original.productId,x.original.sku);if(!p)throw new Error('Returned product '+x.original.name+' no longer exists');p.stock=returnsR3_(p.stock+x.qty);p.updatedAt=iso;moves.push(movement_(++nextMove,p,x.qty,'return',returnNo,iso));rows.push({id:++nextItem,returnId:returnId,invoiceNo:invoiceNo,originalSaleItemId:x.original.id,productId:p.id,sku:p.sku,name:p.name,unit:p.unit,qty:x.qty,unitPrice:x.unitPrice,taxRate:x.taxRate,replacementProductId:x.replacement?x.replacement.id:0,replacementSku:x.replacement?x.replacement.sku:'',replacementName:x.replacement?x.replacement.name:'',replacementQty:x.replacementQty,replacementPrice:x.replacement?x.replacement.price:0,replacementTaxRate:x.replacement?x.replacement.taxRate:0,reason:returnsStr_(req.reason,120)});writeRow_('Products',p._row,p);if(x.replacement){var rp=resolveProduct_(products,x.replacement.id,x.replacement.sku);rp.stock=returnsR3_(rp.stock-x.replacementQty);rp.updatedAt=iso;writeRow_('Products',rp._row,rp);moves.push(movement_(++nextMove,rp,-x.replacementQty,'exchange',returnNo,iso));}});
  returnsAppend_('Returns',[rec]);returnsAppend_('ReturnItems',rows);appendRows_('StockMovements',moves);SpreadsheetApp.flush();return{returnRecord:rec,returnItems:rows,settlementText:difference>0?'Collect '+difference:difference<0?'Refund '+Math.abs(difference):'No balance due'};
}
function returnsSync_(req){var ops=Array.isArray(req.ops)?req.ops.slice(0,50):[],log=returnsRead_('ReturnsSyncLog'),seen={};log.forEach(function(x){seen[x.opId]=x;});var results=[];ops.forEach(function(op){var id=returnsStr_(op&&op.opId,64);if(!id){results.push({opId:'',ok:false,error:'Missing opId'});return;}if(seen[id]){results.push({opId:id,ok:seen[id].ok,duplicate:true,error:seen[id].message||undefined});return;}var res;try{res=returnsCreate_(op.payload||{})||{};res.ok=true;}catch(e){res={ok:false,error:String(e&&e.message||e)};}res.opId=id;returnsAppend_('ReturnsSyncLog',[{opId:id,appliedAt:new Date().toISOString(),ok:res.ok,message:res.error||''}]);seen[id]={ok:res.ok,message:res.error||''};results.push(res);});SpreadsheetApp.flush();return{results:results,version:RETURNS_VERSION};}
